substitutions:
  _REGION: europe-west4
  _GCR_HOST: eu.gcr.io

timeout: 1200s

steps:
# Signal cloud build start
# https://cloud.google.com/sdk/gcloud/reference/logging/write
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  entrypoint: "gcloud"
  id: "log-build-start"
  args:
  - "logging"
  - "write"
  - "build"
  - '{"state": "started", "project_id": "$PROJECT_ID", "build_id": "$BUILD_ID", "branch_name": "$BRANCH_NAME", "tag_name": "$TAG_NAME", "repo_name": "$REPO_NAME", "short_sha": "$SHORT_SHA", "commit_sha": "$COMMIT_SHA"}'
  - "--payload-type=json"

# Build & push docker container image
- name: "gcr.io/kaniko-project/executor:latest"
  id: "build-service"
  args:
  - "--destination=$_GCR_HOST/$PROJECT_ID/$REPO_NAME:latest"
  - "--destination=$_GCR_HOST/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
  - "--cache=true"
  - "--cache-ttl=6h"

# Deploy to Cloud Run
# https://cloud.google.com/sdk/gcloud/reference/run/deploy
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  entrypoint: "gcloud"
  id: "deploy-cloud-run"
  waitFor:
    - "build-service"
  args:
  - "run"
  - "services"
  - "update"
  - "$REPO_NAME"
  - "--platform=managed"
  - "--region=$_REGION"
  - "--image=$_GCR_HOST/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"

# Create Firestore indexes
# https://cloud.google.com/sdk/gcloud/reference/firestore/indexes/composite/create
# https://cloud.google.com/build/docs/configuring-builds/run-bash-scripts
# using breakout syntax to be able to use ||: to prevent the build from failing
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  entrypoint: "bash"
  id: "create-firestore-indexes"
  args:
  - "-c"
# Signal cloud build finished
# https://cloud.google.com/sdk/gcloud/reference/logging/write
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
  entrypoint: "gcloud"
  id: "log-build-end"
  args:
  - "logging"
  - "write"
  - "build"
  - '{"state": "finished", "project_id": "$PROJECT_ID", "build_id": "$BUILD_ID", "branch_name": "$BRANCH_NAME", "tag_name": "$TAG_NAME", "repo_name": "$REPO_NAME", "short_sha": "$SHORT_SHA", "commit_sha": "$COMMIT_SHA"}'
  - "--payload-type=json"