version: '0.0'

services:
  backend:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env.example

  portal:
    build:
      context: .
      dockerfile: src/chemistry_calculator_portal/Dockerfile
      args:
        VITE_WEBSITE_HOST: http://localhost:3000
        VITE_BACKEND_HOST: http://localhost:8000
    ports:
      - 3000:3000
    environment:
      ORIGIN: http://localhost:3000
